import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Nav } from "@/components/Nav/Nav";
import { SITE_NAME, NAV_ITEMS } from "@/config/site";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class">
          <Nav homeLabel={SITE_NAME} items={[...NAV_ITEMS]} />
          {children}
          <footer>
            <div>&copy; {new Date().getFullYear()} Tom&apos;s Portfolio</div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
